### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by chris-barry** [TheFynx/docker-weechat#1]
When I run this, I get:

    error opening terminal unknown

I believe that the run commands need to be passed the -t flag.

(Thank you for this repo by the way, I was about to make something similar and this is exactly what I need :+1: )

**Comment by TheFynx** [comment]
You're absolutely right! I completely forgot to update the README with the correct flags. 

The README is updated (https://github.com/TheFynx/docker-weechat/commit/8c21ae1e16a18304881345da59f0968b877d7c45)

Also you're welcome!
