### ISSUE TITLE
Please retrigger dockerhub build for 1.9.1-r0

### ISSUE THREAD

**Issue by chris-barry** [TheFynx/docker-weechat#2]
^ see title ^

**Comment by TheFynx** [comment]
Re-triggered, but still pulled in 1.7. Seems 1.9.1 is in the edge repo. Going to test adding and edge repo and/or edge image. May choose to build from source. Give me a day or so to get this done.

**Comment by TheFynx** [comment]
There is now a edge tag version of the weechat setup, https://hub.docker.com/r/thefynx/alpine-weechat/tags/ that will have the 1.9.1-r0

Just a quick work around for now.

**Comment by chris-barry** [comment]
Thank you :)

**Comment by TheFynx** [comment]
Latest Alpine how has an even newer version and I have both latest/edge in autobuilds and should hopefully stay updated as alpine updates.
